---
loopback: 70.70.70.70
local_asn: 65070
neighbors:
  - name: aritsa2
    asn: 65080
    peer_ip: 172.16.0.80
    local_ip: 172.16.0.70
  - name: vmx1
    asn: 65030
    peer_ip: 172.16.0.30
    local_ip: 172.16.0.70
  - name: vmx2
    asn: 65040
    peer_ip: 172.16.0.40
    local_ip: 172.16.0.70
